version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: github_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-github-scraper

  analytics_postgres:
    image: postgres:15
    container_name: analytics_postgres
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: analytics
    ports:
      - "5433:5432"
    volumes:
      - analytics_postgres_data:/var/lib/postgresql/data
    networks:
      - api-github-scraper

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - api-github-scraper

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - api-github-scraper

volumes:
  postgres_data:

networks:
  api-github-scraper:
    name: api-github-scraper
    driver: bridge