[project]
name = "api-github-scraper-producer-consumer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "psycopg[binary]>=3.2.9",
    "redis>=6.4.0",
    "requests>=2.32.4",
]
