name: analytics-dashboard
description: Infrastructure for analytics dashboard in AWS
runtime:
  name: python
  options:
    toolchain: uv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
